# Generated by Django 5.2.2 on 2025-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20250603_2255"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
