# Generated by Django 5.2.1 on 2025-06-10 09:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_device_brand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smarthomeuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "智能家居用户",
                "verbose_name_plural": "智能家居用户",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="个人简介"
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="最后登录IP"
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="手机号格式不正确，请输入11位数字",
                        regex="^1[3-9]\\d{9}$",
                    )
                ],
                verbose_name="手机号",
            ),
        ),
        migrations.AddField(
            model_name="smarthomeuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="smarthomeuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="smarthomeuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="smarthomeuser",
            name="permissions",
            field=models.JSONField(default=list, verbose_name="权限列表"),
        ),
        migrations.AlterField(
            model_name="smarthomeuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "管理员"),
                    ("member", "普通成员"),
                    ("guest", "访客"),
                ],
                default="member",
                max_length=10,
                verbose_name="用户角色",
            ),
        ),
    ]
