# Generated by Django 5.2.1 on 2025-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_ip_address_device_port_alter_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default='fd9d59a9-bcb8-4a8b-9791-59e25c8fd45d', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default='0eb5ae69-b644-4989-9602-300f675de7bd', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='1548c97d-9fb6-4a5e-909d-a98dc0197772', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='48a1d0d8-898c-49a6-bbd7-82a80bd02450', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smarthomeuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='smarthomeuser',
            name='id',
            field=models.CharField(default='3c2f6227-0f8a-4a5a-8624-1c0000bc5cc0', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
