# Generated by Django 5.2.1 on 2025-06-13 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_device_id_alter_room_id_alter_scene_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default='4ac6b1d2-1f35-4239-9eee-a5280dfa1f72', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default='fe8befaf-f674-4236-b497-cb2e37801355', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='30ee3869-d7de-4339-8a1d-416a7e16e1a9', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='8a60f2d2-4b10-4c49-a080-8d28a340fc1f', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smarthomeuser',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
