# Generated by Django 5.2.1 on 2025-06-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_device_id_alter_room_id_alter_scene_id_and_more'),
    ]

    operations = [
    ]
