# Generated by Django 5.2.1 on 2025-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default='fb5010c2-fa16-4e49-ab5a-34f1e5eb1808', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default='1e0dbc82-e139-4a9a-8591-a86a4bcc5de2', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='b7751218-5097-4bf0-9609-be7830d26ad2', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='73c610af-dc74-498d-8f3a-b750ef0a2c83', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
