# Generated by Django 5.2.1 on 2025-06-14 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_device_id_alter_room_id_alter_scene_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='f9051ea9-e540-4b7b-9923-367c5b797b67', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='56c1c8d5-c165-4e19-8eeb-6517b11c42a1', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
