# Generated by Django 5.2.1 on 2025-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_device_id_alter_room_id_alter_scene_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='bdbc39c8-235f-4630-adaa-9855daf49120', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='656f2a05-1c41-4ddb-854f-271b426d5d83', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
