# Generated by Django 5.2.1 on 2025-06-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_scene_id_alter_scenedeviceconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='fe405a52-521a-47cb-91fb-50c66f41519b', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='6513db6e-a73c-424f-b152-a01e5fe75d0a', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
