# Generated by Django 5.2.1 on 2025-06-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_scene_id_alter_scenedeviceconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default='f812cd82-d4fe-49ec-a0d8-45781c986f66', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default='aecad451-346b-4fe8-b053-1581f6dd6ff9', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
