# Generated by Django 5.2.1 on 2025-06-15 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_scene_id_alter_scenedeviceconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default=uuid.UUID('3a3b830c-0d2b-49be-b41c-616d062b2554'), editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default=uuid.UUID('b103ff98-fa1b-4134-a9d1-d7ef65213dad'), editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
