# Generated by Django 5.2.1 on 2025-06-15 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_scene_id_alter_scenedeviceconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.CharField(default=uuid.UUID('8f71578b-12b6-42c6-a470-8fbf2de89d44'), editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenedeviceconfig',
            name='id',
            field=models.CharField(default=uuid.UUID('585ebce4-d22b-4d2a-a926-7f14e6205db8'), editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
